language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

install:
  - "gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true"
  - "gem install bundler -v '< 2'"
  - "bundle install --jobs=3 --retry=3"

env:
  -
  - RACK_VERSION=1.3.0
  - RACK_VERSION=1.4.0
  - RACK_VERSION=1.5.0
  - RACK_VERSION=1.6.0
  - RACK_VERSION=2.0.0
  - RAILS_VERSION=4.0.0
  - RAILS_VERSION=4.1.0
  - RAILS_VERSION=4.2.0
  - RAILS_VERSION=5.0.0
  - RAILS_VERSION=5.1.0
  - RAILS_VERSION=5.2.0
  - I18N_VERSION=0.6.0

matrix:
  allow_failures:
    - rvm: 2.4
      env: RAILS_VERSION=4.0.0
    - rvm: 2.4
      env: RAILS_VERSION=4.1.0
    - rvm: 2.5
      env: RAILS_VERSION=4.0.0
    - rvm: 2.5
      env: RAILS_VERSION=4.1.0
    - rvm: 2.6
      env: RAILS_VERSION=4.0.0
    - rvm: 2.6
      env: RAILS_VERSION=4.1.0
    - rvm: 2.7
      env: RAILS_VERSION=4.0.0
    - rvm: 2.7
      env: RAILS_VERSION=4.1.0
    - rvm: 2.7
      env: RAILS_VERSION=4.2.0

script: "bundle exec rake spec"

branches:
  only:
    - master
